## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Sun Oct  4 21:28:40 2026
## 
set sdc_version 1.4
current_design Final_System_dft
create_clock [get_ports {scan_CLK}]  -name DFTCLK -period 1000 -waveform {0 500}
set_clock_latency -min 0 [get_clocks {DFTCLK}]
set_clock_latency -max 0 [get_clocks {DFTCLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {DFTCLK}]
create_clock [get_ports {UART_CLK}]  -name UART_CLK -period 271.297 -waveform {0 135.648}
set_clock_latency -min 0 [get_clocks {UART_CLK}]
set_clock_latency -max 0 [get_clocks {UART_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {UART_CLK}]
create_clock [get_ports {REF_CLK}]  -name REF_CLK -period 20 -waveform {0 10}
set_clock_latency -min 0 [get_clocks {REF_CLK}]
set_clock_latency -max 0 [get_clocks {REF_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {REF_CLK}]
create_generated_clock -name ALU_CLK -source [get_ports {REF_CLK}] -divide_by 1 -master_clock [get_clocks {REF_CLK}] -add [get_pins {CLK_GATE/U0_TLATNCAX12M/ECK}]
create_generated_clock -name TX_CLK -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_CLK}] -add [get_pins {ClkDiv_TX/U55/Y}]
create_generated_clock -name RX_CLK -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_CLK}] -add [get_pins {ClkDiv_RX/U55/Y}]
set_propagated_clock  [get_pins {CLK_GATE/U0_TLATNCAX12M/ECK}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_pins {ClkDiv_RX/U55/Y}]
set_propagated_clock  [get_ports {REF_CLK}]
set_propagated_clock  [get_ports {scan_CLK}]
set_propagated_clock  [get_pins {ClkDiv_TX/U55/Y}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {RX_IN}]
set_load -pin_load -max  0.1  [get_ports {SO[3]}]
set_load -pin_load -min  0.1  [get_ports {SO[3]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_load -pin_load -max  0.1  [get_ports {TX_OUT}]
set_load -pin_load -min  0.1  [get_ports {TX_OUT}]
set_load -pin_load -max  0.1  [get_ports {parity_error}]
set_load -pin_load -min  0.1  [get_ports {parity_error}]
set_load -pin_load -max  0.1  [get_ports {stop_error}]
set_load -pin_load -min  0.1  [get_ports {stop_error}]
set_case_analysis 1 [get_ports {SE}]
set_case_analysis 1 [get_ports {test_mode}]
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -max -name tsmc13_wl10
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min -name tsmc13_wl10
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SI[3]}]
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SI[1]}]
set_input_delay -add_delay 54.2594 -clock [get_clocks {RX_CLK}] [get_ports {RX_IN}]
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SE}]
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {test_mode}]
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SI[2]}]
set_input_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SI[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SO[2]}]
set_output_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SO[0]}]
set_output_delay -add_delay 1736.3 -clock [get_clocks {TX_CLK}] [get_ports {TX_OUT}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {RX_CLK}] [get_ports {stop_error}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {RX_CLK}] [get_ports {parity_error}]
set_output_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SO[3]}]
set_output_delay -add_delay 200 -clock [get_clocks {DFTCLK}] [get_ports {SO[1]}]
set_clock_uncertainty 0.1 -hold [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {REF_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {REF_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {TX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {TX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {DFTCLK}]
set_clock_uncertainty 0.025 -setup [get_clocks {DFTCLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {RX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {RX_CLK}]
set_clock_groups -name ALU_CLK_1 -logically_exclusive  -group  [get_clocks {ALU_CLK}] -group  [get_clocks {DFTCLK}]
set_clock_groups -name REF_CLK_1 -logically_exclusive  -group  [get_clocks {REF_CLK}] -group  [get_clocks {DFTCLK}]
set_clock_groups -name REF_CLK_2 -asynchronous  -group  [get_clocks {ALU_CLK REF_CLK}] -group  [get_clocks {RX_CLK TX_CLK UART_CLK}]
set_clock_groups -name UART_CLK_1 -logically_exclusive  -group  [get_clocks {UART_CLK}] -group  [get_clocks {DFTCLK}]
set_clock_groups -name RX_CLK_1 -logically_exclusive  -group  [get_clocks {RX_CLK}] -group  [get_clocks {DFTCLK}]
set_clock_groups -name TX_CLK_1 -logically_exclusive  -group  [get_clocks {TX_CLK}] -group  [get_clocks {DFTCLK}]
